# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1051, 561))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/MainBackground.jpeg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 170, 361, 371))
        self.label_2.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgba(115, 80, 104, 0.4);\n"
"\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_Date = QtWidgets.QLabel(self.centralwidget)
        self.label_Date.setGeometry(QtCore.QRect(680, 170, 361, 61))
        self.label_Date.setStyleSheet("QLabel{\n"
"    font-family: Arial;\n"
"    font-weight: 700;\n"
"    font-size: 24px;\n"
"    color: white;\n"
"}")
        self.label_Date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Date.setWordWrap(False)
        self.label_Date.setObjectName("label_Date")
        self.label_Temperature = QtWidgets.QLabel(self.centralwidget)
        self.label_Temperature.setGeometry(QtCore.QRect(680, 230, 361, 61))
        self.label_Temperature.setStyleSheet("QLabel{\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    color: rgb(202, 202, 202);\n"
"    background-color: rgba(50, 45, 68, 0.5);\n"
"}")
        self.label_Temperature.setObjectName("label_Temperature")
        self.label_Humidity = QtWidgets.QLabel(self.centralwidget)
        self.label_Humidity.setGeometry(QtCore.QRect(680, 300, 361, 61))
        self.label_Humidity.setStyleSheet("QLabel{\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    color: rgb(202, 202, 202);\n"
"    background-color: rgba(50, 45, 68, 0.5);\n"
"}")
        self.label_Humidity.setObjectName("label_Humidity")
        self.label_Wind_Speed = QtWidgets.QLabel(self.centralwidget)
        self.label_Wind_Speed.setGeometry(QtCore.QRect(680, 370, 361, 61))
        self.label_Wind_Speed.setStyleSheet("QLabel{\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    color: rgb(202, 202, 202);\n"
"    background-color: rgba(50, 45, 68, 0.5);\n"
"}")
        self.label_Wind_Speed.setObjectName("label_Wind_Speed")
        self.label_Clouds = QtWidgets.QLabel(self.centralwidget)
        self.label_Clouds.setGeometry(QtCore.QRect(680, 440, 361, 61))
        self.label_Clouds.setStyleSheet("QLabel{\n"
"    font-family: Arial;\n"
"    font-size: 18px;\n"
"    color: rgb(202, 202, 202);\n"
"    background-color: rgba(50, 45, 68, 0.5);\n"
"}")
        self.label_Clouds.setObjectName("label_Clouds")
        self.lineEdit_CityaName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CityaName.setGeometry(QtCore.QRect(680, 80, 281, 61))
        self.lineEdit_CityaName.setStyleSheet("QLineEdit{\n"
"    color: rgb(0, 255, 255);\n"
"    font: 14pt \"Arial\";\n"
"    background-color: rgba(47, 47, 47, 0.5);\n"
"}")
        self.lineEdit_CityaName.setText("")
        self.lineEdit_CityaName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_CityaName.setObjectName("lineEdit_CityaName")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 30, 281, 51))
        self.label_3.setStyleSheet("QLabel{\n"
"    font-size: 25px;\n"
"    font-weight: 1000;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_Update = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Update.setGeometry(QtCore.QRect(980, 80, 51, 51))
        self.pushButton_Update.setStyleSheet("QPushButton{\n"
"    background-color: rgb(121, 75, 86);\n"
"}")
        self.pushButton_Update.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/update1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Update.setIcon(icon)
        self.pushButton_Update.setIconSize(QtCore.QSize(43, 43))
        self.pushButton_Update.setShortcut("")
        self.pushButton_Update.setObjectName("pushButton_Update")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Date.setText(_translate("MainWindow", "Date"))
        self.label_Temperature.setText(_translate("MainWindow", "Temperature:"))
        self.label_Humidity.setText(_translate("MainWindow", "Humidity:"))
        self.label_Wind_Speed.setText(_translate("MainWindow", "Wind speed:"))
        self.label_Clouds.setText(_translate("MainWindow", "Clouds:"))
        self.label_3.setText(_translate("MainWindow", "City"))
